import type {
  CareerDirectionPlan,
  CareerWorkbench,
  CompanyProfile,
  InterviewQuestion,
  JobPosting,
  LearningMilestone,
  UserSkill,
} from './types';

export const CAREERS_STORAGE_KEY = 'careers-workbench-demo';

export const DEFAULT_USER_SKILLS: UserSkill[] = [
  { id: 'skill-python', name: 'Python', category: '编程基础', level: 72, targetLevel: 85, priority: 'high' },
  { id: 'skill-go', name: 'Go', category: '编程基础', level: 48, targetLevel: 78, priority: 'medium' },
  { id: 'skill-linux', name: 'Linux', category: '系统基础', level: 68, targetLevel: 82, priority: 'high' },
  { id: 'skill-web', name: 'Web 安全', category: '攻防能力', level: 74, targetLevel: 86, priority: 'high' },
  { id: 'skill-pentest', name: '渗透测试', category: '攻防能力', level: 62, targetLevel: 82, priority: 'medium' },
  { id: 'skill-ir', name: '应急响应', category: '安全运营', level: 54, targetLevel: 78, priority: 'medium' },
  { id: 'skill-threat', name: '威胁情报', category: '安全运营', level: 46, targetLevel: 74, priority: 'medium' },
  { id: 'skill-cloud', name: '云原生安全', category: '云安全', level: 42, targetLevel: 82, priority: 'high' },
  { id: 'skill-k8s', name: 'Kubernetes', category: '云安全', level: 38, targetLevel: 80, priority: 'high' },
  { id: 'skill-ebpf', name: 'eBPF', category: '安全开发', level: 24, targetLevel: 70, priority: 'high' },
  { id: 'skill-sast', name: 'SAST/DAST', category: '安全开发', level: 50, targetLevel: 78, priority: 'medium' },
  { id: 'skill-ai', name: 'AI 安全', category: 'AI 安全', level: 44, targetLevel: 86, priority: 'high' },
  { id: 'skill-adv', name: '对抗样本', category: 'AI 安全', level: 36, targetLevel: 82, priority: 'high' },
  { id: 'skill-llm', name: 'LLM 安全', category: 'AI 安全', level: 40, targetLevel: 84, priority: 'high' },
  { id: 'skill-ics', name: '工控协议', category: '工控安全', level: 28, targetLevel: 76, priority: 'medium' },
  { id: 'skill-crypto', name: '密码学基础', category: '理论基础', level: 60, targetLevel: 72, priority: 'low' },
  { id: 'skill-compliance', name: '安全合规', category: '合规治理', level: 48, targetLevel: 72, priority: 'low' },
  { id: 'skill-data', name: '数据安全', category: '数据安全', level: 45, targetLevel: 78, priority: 'medium' },
];

export const MOCK_COMPANIES: CompanyProfile[] = [
  {
    id: 'company-qianxin',
    name: '奇安信',
    tier: 'A',
    cityList: ['北京', '深圳', '成都'],
    businessAreas: ['终端安全', '安全服务', '威胁情报'],
    securityFocus: ['攻防演练', '漏洞研究', '安全运营'],
    techStack: ['Python', 'Go', 'Linux', '威胁情报', 'SAST/DAST'],
    hiringPreference: ['项目经历清晰', '攻防实践扎实', '能写技术报告'],
    cultureTags: ['安全氛围强', '项目密集', '成长快'],
    openJobs: ['job-ai-research', 'job-pentest'],
    matchScore: 91,
    favorited: false,
  },
  {
    id: 'company-sangfor',
    name: '深信服',
    tier: 'A',
    cityList: ['深圳', '长沙', '南京'],
    businessAreas: ['网络安全产品', '云安全', '终端安全'],
    securityFocus: ['安全开发', '漏洞挖掘', '云原生安全'],
    techStack: ['Go', 'Linux', 'Kubernetes', 'eBPF', 'Web 安全'],
    hiringPreference: ['工程能力强', '能做产品化实现', '熟悉网络协议'],
    cultureTags: ['产品导向', '工程落地', '校招体系成熟'],
    openJobs: ['job-cloud-dev', 'job-security-dev'],
    matchScore: 88,
    favorited: false,
  },
  {
    id: 'company-360',
    name: '360',
    tier: 'A',
    cityList: ['北京', '上海'],
    businessAreas: ['威胁情报', '漏洞研究', '安全大数据'],
    securityFocus: ['安全研究', '工控安全', '红队/蓝队'],
    techStack: ['Python', 'Linux', '渗透测试', '工控协议', '威胁情报'],
    hiringPreference: ['研究深度', '漏洞复现能力', '公开输出'],
    cultureTags: ['研究资源丰富', '方向细分', '技术挑战高'],
    openJobs: ['job-ics', 'job-redblue'],
    matchScore: 86,
    favorited: false,
  },
  {
    id: 'company-aliyun',
    name: '阿里云安全',
    tier: 'S',
    cityList: ['杭州', '北京', '上海'],
    businessAreas: ['云安全', '数据安全', '基础设施安全'],
    securityFocus: ['云原生安全', '身份权限', '安全开发'],
    techStack: ['Go', 'Kubernetes', 'eBPF', '数据安全', '安全合规'],
    hiringPreference: ['云原生基础扎实', '系统设计能力', '自动化工程经验'],
    cultureTags: ['业务规模大', '平台复杂', '工程要求高'],
    openJobs: ['job-cloud-dev', 'job-data-security'],
    matchScore: 92,
    favorited: false,
  },
  {
    id: 'company-tencent',
    name: '腾讯安全',
    tier: 'S',
    cityList: ['深圳', '广州', '上海'],
    businessAreas: ['业务安全', '游戏安全', '云安全'],
    securityFocus: ['安全运营', '安全开发', '风控对抗'],
    techStack: ['Go', 'Python', 'Linux', '应急响应', 'Web 安全'],
    hiringPreference: ['业务理解好', '协作能力强', '攻防基础扎实'],
    cultureTags: ['业务场景多', '岗位多样', '团队协作强'],
    openJobs: ['job-soc', 'job-security-dev'],
    matchScore: 87,
    favorited: false,
  },
  {
    id: 'company-ant',
    name: '蚂蚁安全',
    tier: 'S',
    cityList: ['杭州', '上海'],
    businessAreas: ['金融科技安全', '数据安全', 'AI 风控'],
    securityFocus: ['AI 安全', '数据安全', '合规治理'],
    techStack: ['Python', 'AI 安全', 'LLM 安全', '数据安全', '安全合规'],
    hiringPreference: ['研究能力强', '关注合规边界', '表达严谨'],
    cultureTags: ['业务敏感度高', '规范要求高', '前沿方向多'],
    openJobs: ['job-ai-research', 'job-data-security'],
    matchScore: 90,
    favorited: false,
  },
  {
    id: 'company-huawei',
    name: '华为安全',
    tier: 'S',
    cityList: ['深圳', '南京', '成都'],
    businessAreas: ['终端安全', '云安全', '可信计算'],
    securityFocus: ['安全开发', '密码学基础', '安全合规'],
    techStack: ['Go', 'Linux', '密码学基础', 'SAST/DAST', 'Kubernetes'],
    hiringPreference: ['基础扎实', '工程规范', '长期投入'],
    cultureTags: ['工程体系强', '要求稳定', '安全边界清晰'],
    openJobs: ['job-security-dev', 'job-compliance'],
    matchScore: 85,
    favorited: false,
  },
  {
    id: 'company-bytedance',
    name: '字节跳动安全',
    tier: 'S',
    cityList: ['北京', '上海', '深圳'],
    businessAreas: ['业务安全', 'AI 平台安全', '基础架构安全'],
    securityFocus: ['AI 安全', '云原生安全', '安全开发'],
    techStack: ['Go', 'Python', 'Kubernetes', 'LLM 安全', 'eBPF'],
    hiringPreference: ['学习速度快', '工程和研究兼备', '能处理复杂业务场景'],
    cultureTags: ['节奏快', '场景复杂', '技术前沿'],
    openJobs: ['job-ai-research', 'job-cloud-dev'],
    matchScore: 93,
    favorited: false,
  },
  {
    id: 'company-nsfocus',
    name: '绿盟科技',
    tier: 'A',
    cityList: ['北京', '成都', '南京'],
    businessAreas: ['漏洞研究', '安全服务', '工控安全'],
    securityFocus: ['渗透测试', '工控安全', '安全合规'],
    techStack: ['Web 安全', '渗透测试', '工控协议', '安全合规'],
    hiringPreference: ['安全服务经验', '报告能力', '客户场景理解'],
    cultureTags: ['行业积累深', '项目类型多', '适合打基础'],
    openJobs: ['job-pentest', 'job-ics', 'job-compliance'],
    matchScore: 82,
    favorited: false,
  },
  {
    id: 'company-venustech',
    name: '启明星辰',
    tier: 'A',
    cityList: ['北京', '上海', '广州'],
    businessAreas: ['安全运营', '合规审计', '数据安全'],
    securityFocus: ['安全运营', '安全合规', '数据安全'],
    techStack: ['应急响应', '威胁情报', '安全合规', '数据安全'],
    hiringPreference: ['稳定细致', '流程意识强', '能沉淀运营经验'],
    cultureTags: ['体系成熟', '安全运营强', '适合长期成长'],
    openJobs: ['job-soc', 'job-compliance', 'job-data-security'],
    matchScore: 80,
    favorited: false,
  },
];

export const MOCK_JOBS: JobPosting[] = [
  {
    id: 'job-ai-research',
    title: 'AI 安全研究员',
    companyId: 'company-bytedance',
    companyName: '字节跳动安全',
    direction: 'AI 安全',
    city: '北京',
    salaryMin: 28,
    salaryMax: 45,
    salaryText: '28-45K',
    jobType: '校招',
    education: '本科及以上',
    experience: '安全竞赛或论文复现经历优先',
    tags: ['热门', 'AI 安全', 'LLM 安全', '研究型'],
    responsibilities: ['跟踪 LLM Prompt Injection、越狱和模型对齐风险', '复现并评估对抗样本攻击与防御方法', '输出评估报告、检测工具和安全基线'],
    requirements: ['熟悉 Python 和 PyTorch', '理解常见 Web 安全与模型安全风险', '能阅读英文论文并完成复现'],
    skillKeywords: ['Python', 'AI 安全', '对抗样本', 'LLM 安全', 'Web 安全'],
    matchScore: 92,
    heatScore: 96,
    source: '企业校招公开页',
    sourceUrl: 'https://example.com/jobs/ai-security',
    updatedAt: '2026-04-22',
    favorited: false,
  },
  {
    id: 'job-pentest',
    title: '渗透测试工程师',
    companyId: 'company-qianxin',
    companyName: '奇安信',
    direction: '红队/蓝队',
    city: '北京',
    salaryMin: 15,
    salaryMax: 28,
    salaryText: '15-28K',
    jobType: '校招',
    education: '本科及以上',
    experience: 'CTF 或实战项目优先',
    tags: ['校招', '攻防', 'Web 安全'],
    responsibilities: ['负责 Web、内网和云资产渗透测试', '撰写漏洞复现和修复建议报告', '参与攻防演练与安全评估'],
    requirements: ['熟悉 SQL 注入、XSS、SSRF 等漏洞', '熟悉 Linux 与常见提权方法', '具备良好报告表达能力'],
    skillKeywords: ['Web 安全', '渗透测试', 'Linux', '应急响应', '威胁情报'],
    matchScore: 86,
    heatScore: 89,
    source: '招聘平台聚合',
    sourceUrl: 'https://example.com/jobs/pentest',
    updatedAt: '2026-04-20',
    favorited: false,
  },
  {
    id: 'job-security-dev',
    title: '安全开发工程师',
    companyId: 'company-huawei',
    companyName: '华为安全',
    direction: '安全开发',
    city: '深圳',
    salaryMin: 22,
    salaryMax: 38,
    salaryText: '22-38K',
    jobType: '校招',
    education: '本科及以上',
    experience: '安全工具或平台开发经验优先',
    tags: ['安全开发', '平台工具', '工程能力'],
    responsibilities: ['开发安全扫描、策略编排和自动化检测工具', '参与 SAST/DAST 能力建设', '支撑安全能力产品化落地'],
    requirements: ['熟悉 Go 或 Python', '了解 Linux、网络协议和安全漏洞原理', '具备良好工程规范意识'],
    skillKeywords: ['Go', 'Python', 'Linux', 'SAST/DAST', 'Web 安全'],
    matchScore: 84,
    heatScore: 88,
    source: '企业校招公开页',
    sourceUrl: 'https://example.com/jobs/security-dev',
    updatedAt: '2026-04-21',
    favorited: false,
  },
  {
    id: 'job-cloud-dev',
    title: '云安全工程师',
    companyId: 'company-aliyun',
    companyName: '阿里云安全',
    direction: '云安全',
    city: '杭州',
    salaryMin: 25,
    salaryMax: 42,
    salaryText: '25-42K',
    jobType: '社招',
    education: '本科及以上',
    experience: '1-3 年云平台或容器安全经验',
    tags: ['云原生', 'Kubernetes', '高薪'],
    responsibilities: ['建设云上身份权限和容器安全检测能力', '分析 Kubernetes 风险配置和容器逃逸路径', '推动云安全自动化治理'],
    requirements: ['熟悉 Kubernetes、Linux 和网络基础', '理解云原生安全风险', '有 Go 或 eBPF 经验加分'],
    skillKeywords: ['云原生安全', 'Kubernetes', 'Linux', 'Go', 'eBPF'],
    matchScore: 78,
    heatScore: 94,
    source: '招聘平台聚合',
    sourceUrl: 'https://example.com/jobs/cloud-security',
    updatedAt: '2026-04-23',
    favorited: false,
  },
  {
    id: 'job-soc',
    title: '安全运营工程师',
    companyId: 'company-tencent',
    companyName: '腾讯安全',
    direction: '安全运营',
    city: '深圳',
    salaryMin: 16,
    salaryMax: 30,
    salaryText: '16-30K',
    jobType: '校招',
    education: '本科及以上',
    experience: '安全运营实习或蓝队经验优先',
    tags: ['SOC', '蓝队', '应急响应'],
    responsibilities: ['负责告警研判、日志分析和应急处置', '沉淀检测规则和响应流程', '参与安全运营自动化建设'],
    requirements: ['熟悉 Linux、网络协议和日志分析', '理解常见攻击链', '具备应急响应与报告能力'],
    skillKeywords: ['应急响应', '威胁情报', 'Linux', 'Web 安全', '安全合规'],
    matchScore: 82,
    heatScore: 83,
    source: '企业招聘页',
    sourceUrl: 'https://example.com/jobs/soc',
    updatedAt: '2026-04-19',
    favorited: false,
  },
  {
    id: 'job-ics',
    title: '工控安全研究员',
    companyId: 'company-360',
    companyName: '360',
    direction: '工控安全',
    city: '北京',
    salaryMin: 18,
    salaryMax: 32,
    salaryText: '18-32K',
    jobType: '校招',
    education: '本科及以上',
    experience: '工控协议分析或漏洞复现经验优先',
    tags: ['工控安全', '协议分析', '研究型'],
    responsibilities: ['分析 Modbus、OPC UA 等工控协议风险', '复现工控漏洞并输出防护建议', '建设工控安全测试环境'],
    requirements: ['理解网络协议与逆向基础', '熟悉 Linux 和 Python', '对工业互联网安全有研究兴趣'],
    skillKeywords: ['工控协议', 'Python', 'Linux', '渗透测试', '威胁情报'],
    matchScore: 76,
    heatScore: 78,
    source: '招聘平台聚合',
    sourceUrl: 'https://example.com/jobs/ics',
    updatedAt: '2026-04-18',
    favorited: false,
  },
  {
    id: 'job-data-security',
    title: '数据安全工程师',
    companyId: 'company-ant',
    companyName: '蚂蚁安全',
    direction: '数据安全',
    city: '杭州',
    salaryMin: 22,
    salaryMax: 40,
    salaryText: '22-40K',
    jobType: '实习',
    education: '本科及以上',
    experience: '数据治理或隐私计算项目优先',
    tags: ['数据安全', '隐私保护', '实习'],
    responsibilities: ['参与数据分类分级、权限治理和审计能力建设', '分析数据泄露风险并给出整改建议', '支撑合规检查和安全评估'],
    requirements: ['理解数据安全生命周期', '熟悉 Python 和 SQL', '了解安全合规要求'],
    skillKeywords: ['数据安全', '安全合规', 'Python', '密码学基础', 'SAST/DAST'],
    matchScore: 80,
    heatScore: 82,
    source: '企业实习公开页',
    sourceUrl: 'https://example.com/jobs/data-security',
    updatedAt: '2026-04-17',
    favorited: false,
  },
  {
    id: 'job-compliance',
    title: '安全合规工程师',
    companyId: 'company-venustech',
    companyName: '启明星辰',
    direction: '安全合规',
    city: '南京',
    salaryMin: 12,
    salaryMax: 22,
    salaryText: '12-22K',
    jobType: '校招',
    education: '本科及以上',
    experience: '等保测评或合规实习优先',
    tags: ['合规治理', '等保', '文档能力'],
    responsibilities: ['参与等保、数据安全和隐私合规评估', '整理测评材料与整改建议', '支撑客户安全制度建设'],
    requirements: ['熟悉网络安全法、数据安全法基本要求', '表达严谨，文档能力好', '了解基础安全技术'],
    skillKeywords: ['安全合规', '数据安全', '密码学基础', 'Web 安全', '应急响应'],
    matchScore: 74,
    heatScore: 70,
    source: '招聘平台聚合',
    sourceUrl: 'https://example.com/jobs/compliance',
    updatedAt: '2026-04-15',
    favorited: false,
  },
];

export const MOCK_INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  {
    id: 'q-https-mitm',
    direction: '安全开发',
    difficulty: '基础',
    topic: '网络协议',
    question: 'HTTPS 握手过程中有哪些中间人攻击风险？如何防护？',
    answer: '核心风险包括证书伪造、降级攻击、弱加密套件和客户端证书校验缺失。防护重点是严格证书链校验、启用 HSTS、禁用弱协议和弱套件，并对敏感客户端使用证书锁定。',
    strategy: '先讲 TLS 握手流程，再按风险点映射防护手段，最后补充真实排查经验。',
    tags: ['HTTPS', 'TLS', '中间人攻击'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-sqli',
    direction: '红队/蓝队',
    difficulty: '基础',
    topic: 'Web 漏洞',
    question: 'SQL 注入的原理是什么？常见防御手段有哪些？',
    answer: 'SQL 注入源于用户输入被拼接进 SQL 语句并改变语义。防御包括参数化查询、输入校验、最小权限、错误信息收敛、WAF 辅助检测和安全测试覆盖。',
    strategy: '不要只背定义，要说明布尔、联合、时间盲注等利用方式和防御优先级。',
    tags: ['SQL 注入', 'Web 安全', '参数化'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-xss-csrf',
    direction: '红队/蓝队',
    difficulty: '基础',
    topic: 'Web 漏洞',
    question: 'XSS 和 CSRF 的区别是什么？分别如何防护？',
    answer: 'XSS 是注入脚本影响用户浏览器执行环境，CSRF 是利用用户已登录态发起非预期请求。XSS 重点是输出编码、CSP、输入清洗；CSRF 重点是 token、SameSite、二次校验。',
    strategy: '用攻击目标、触发条件、利用结果和防护方案四个维度对比。',
    tags: ['XSS', 'CSRF', '浏览器安全'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-ssrf',
    direction: '红队/蓝队',
    difficulty: '进阶',
    topic: 'Web 漏洞',
    question: 'SSRF 常见利用路径和防护策略有哪些？',
    answer: 'SSRF 可用于访问内网服务、云元数据接口、端口探测和协议绕过。防护需要 URL 白名单、DNS 解析校验、内网地址阻断、协议限制和云元数据保护。',
    strategy: '重点讲绕过方式和服务端出口控制，体现实战理解。',
    tags: ['SSRF', '内网', '云安全'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-linux-privesc',
    direction: '红队/蓝队',
    difficulty: '实战',
    topic: '主机安全',
    question: 'Linux 权限与提权常见检查项有哪些？',
    answer: '常见检查包括 SUID 文件、sudo 配置、计划任务、内核版本、敏感文件权限、环境变量劫持、服务配置和凭据泄露。',
    strategy: '按信息收集、漏洞利用、权限维持和痕迹清理说明，不展开非法细节。',
    tags: ['Linux', '提权', '主机安全'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-lateral',
    direction: '红队/蓝队',
    difficulty: '实战',
    topic: '内网安全',
    question: '内网横向移动的思路和防护重点是什么？',
    answer: '横向移动依赖凭据、权限关系、远程管理协议和信任链。防护重点是凭据保护、最小权限、网络分区、异常登录检测和高危协议审计。',
    strategy: '回答时强调检测和防护视角，避免只讲攻击链。',
    tags: ['内网', '横向移动', '蓝队'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-container-escape',
    direction: '云安全',
    difficulty: '实战',
    topic: '容器安全',
    question: '云原生容器逃逸常见成因有哪些？',
    answer: '成因包括特权容器、宿主机敏感目录挂载、危险 capability、容器运行时漏洞和 Kubernetes 配置不当。防护需要最小权限、镜像扫描、运行时监控和准入控制。',
    strategy: '结合配置风险和运行时风险说明，不只讲单个 CVE。',
    tags: ['容器逃逸', 'Kubernetes', '云原生'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-k8s-rbac',
    direction: '云安全',
    difficulty: '系统设计',
    topic: 'Kubernetes',
    question: 'Kubernetes RBAC 安全如何设计？',
    answer: '应按命名空间和职责拆分角色，避免 cluster-admin 泛用，限制 service account 权限，审计高危 verbs，并结合准入控制和权限基线巡检。',
    strategy: '从身份、权限、资源范围和审计四个层面组织答案。',
    tags: ['Kubernetes', 'RBAC', '权限治理'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-waf',
    direction: '安全开发',
    difficulty: '系统设计',
    topic: '安全产品',
    question: '如何设计一个 WAF，并评估它的有效性？',
    answer: 'WAF 设计包括流量解析、规则匹配、语义检测、异常评分、误报反馈和策略发布。评估指标包括检出率、误报率、延迟、吞吐和绕过样本覆盖。',
    strategy: '先给架构，再讲指标和权衡，体现产品化思维。',
    tags: ['WAF', '安全开发', '系统设计'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-prompt-injection',
    direction: 'AI 安全',
    difficulty: '科研',
    topic: 'LLM 安全',
    question: 'LLM Prompt Injection 的风险场景和缓解思路是什么？',
    answer: '风险包括指令覆盖、工具滥用、数据泄露和越权调用。缓解思路包括输入隔离、工具权限收敛、上下文分层、输出审计和对抗样本评测。',
    strategy: '结合代理工具调用场景，说明为什么传统输入过滤不够。',
    tags: ['LLM 安全', 'Prompt Injection', 'AI 安全'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-fgsm-pgd',
    direction: 'AI 安全',
    difficulty: '科研',
    topic: '对抗样本',
    question: 'FGSM 和 PGD 的核心区别是什么？',
    answer: 'FGSM 是单步梯度符号攻击，速度快但强度有限；PGD 是多步迭代攻击，通常在约束范围内更强，可用于更严格的鲁棒性评估。',
    strategy: '用目标函数、迭代方式、扰动约束和评估意义来回答。',
    tags: ['FGSM', 'PGD', '对抗样本'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-modbus',
    direction: '工控安全',
    difficulty: '进阶',
    topic: '工控协议',
    question: 'Modbus 协议有哪些安全风险？',
    answer: 'Modbus 缺少认证和加密，容易受到未授权读写、命令篡改、重放和资产扫描影响。防护可从网络隔离、白名单、工业防火墙、协议审计和异常检测入手。',
    strategy: '先讲协议特点，再讲风险和补偿控制。',
    tags: ['Modbus', '工控协议', '工业互联网'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-alert-noise',
    direction: '安全运营',
    difficulty: '系统设计',
    topic: 'SOC',
    question: '安全运营告警降噪如何设计？',
    answer: '可通过资产重要性、告警聚合、规则置信度、威胁情报、行为基线和处置反馈形成评分机制，减少重复告警并提升高危事件优先级。',
    strategy: '按数据源、规则、评分、闭环反馈展开，体现运营体系思维。',
    tags: ['安全运营', '告警降噪', 'SOC'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-stride',
    direction: '安全合规',
    difficulty: '进阶',
    topic: '威胁建模',
    question: 'STRIDE 威胁建模如何用于业务系统评审？',
    answer: 'STRIDE 从伪造、篡改、抵赖、信息泄露、拒绝服务、权限提升六类威胁出发，结合数据流图识别风险并映射安全控制。',
    strategy: '回答时给出一个登录或支付场景示例，会更有说服力。',
    tags: ['STRIDE', '威胁建模', '合规'],
    mastered: false,
    favorited: false,
  },
  {
    id: 'q-zero-trust',
    direction: '安全研究',
    difficulty: '进阶',
    topic: '安全架构',
    question: '零信任架构的核心原则是什么？如何落地？',
    answer: '核心原则是永不默认信任、持续验证、最小权限和动态授权。落地可从身份统一、设备可信、资源分级、访问代理、策略引擎和审计闭环开始。',
    strategy: '把理念转成可实施组件，避免停留在口号层面。',
    tags: ['零信任', '架构', '访问控制'],
    mastered: false,
    favorited: false,
  },
];

export const DEFAULT_LEARNING_PATH: LearningMilestone[] = [
  {
    id: 'milestone-30',
    phase: '30天',
    title: '补齐 AI 安全与 Web 安全基础',
    description: '围绕目标岗位先建立术语、攻击面和基础复现实验能力。',
    relatedSkills: ['AI 安全', 'Web 安全', 'Python'],
    resources: ['OWASP Top 10', 'Prompt Injection 公开案例', 'PyTorch 官方教程'],
    tasks: ['整理 10 个 LLM 安全案例', '复现 2 个 Web 漏洞', '输出一篇学习笔记'],
    completed: false,
    dueText: '第 1-4 周',
  },
  {
    id: 'milestone-60',
    phase: '60天',
    title: '完成对抗样本与 LLM 安全复现',
    description: '形成可展示的实验结果和代码仓库。',
    relatedSkills: ['对抗样本', 'LLM 安全', 'Python'],
    resources: ['FGSM/PGD 经典论文', 'LLM 安全评测基准', 'GitHub 安全复现仓库'],
    tasks: ['复现 FGSM/PGD', '完成 Prompt Injection 测试集', '整理 README 和实验图表'],
    completed: false,
    dueText: '第 5-8 周',
  },
  {
    id: 'milestone-90',
    phase: '90天',
    title: '沉淀岗位相关项目经历',
    description: '把学习成果转成简历可写的项目表达。',
    relatedSkills: ['AI 安全', 'SAST/DAST', 'Web 安全'],
    resources: ['STAR 简历表达模板', '安全评估报告样例', '开源项目 issue'],
    tasks: ['完成一个小型安全评估工具', '写出项目量化指标', '完成简历第一版'],
    completed: false,
    dueText: '第 9-12 周',
  },
  {
    id: 'milestone-180',
    phase: '180天',
    title: '完成投递与面试闭环',
    description: '围绕目标公司完成投递材料、面试题和复盘记录。',
    relatedSkills: ['LLM 安全', '威胁建模', '安全开发'],
    resources: ['企业校招题库', '模拟面试记录', '技术博客发布平台'],
    tasks: ['收藏 8 家目标公司', '完成 30 道面试题', '投递并复盘 5 次面试'],
    completed: false,
    dueText: '第 13-24 周',
  },
];

export const DEFAULT_DIRECTION_PLANS: CareerDirectionPlan[] = [
  {
    id: 'plan-research',
    type: '科研路线',
    title: 'AI 安全研究助理 -> 安全实验室研究员',
    summary: '适合继续强化论文复现、评测基准和开源工具输出。',
    fitScore: 84,
    milestones: ['3 个月内完成 2 篇论文复现', '6 个月内形成可展示实验报告', '争取实验室实习或科研助理机会'],
    nextActions: ['整理 LLM 安全阅读清单', '把现有项目改成评测工具', '联系导师或实验室师兄师姐'],
    risks: ['论文深度不足', '工程产出不够可展示', '投递窗口偏窄'],
  },
  {
    id: 'plan-industry',
    type: '工业路线',
    title: '安全开发/AI 安全工程师 -> 平台安全骨干',
    summary: '适合用工程项目和安全工具证明岗位适配度。',
    fitScore: 88,
    milestones: ['补齐 Go/Kubernetes 基础', '完成一个安全工具项目', '针对 6 家目标公司定制简历'],
    nextActions: ['把简历项目改成 STAR 表达', '完成云安全与 WAF 系统设计题', '准备校招笔试和面试复盘'],
    risks: ['云原生技能短板明显', '项目指标不够量化', '面试表达需要训练'],
  },
  {
    id: 'plan-hybrid',
    type: '复合路线',
    title: '企业安全研究院 -> 产学研复合型人才',
    summary: '适合同时保留研究深度和产品化落地能力。',
    fitScore: 91,
    milestones: ['完成研究复现与工具化封装', '输出技术博客和开源仓库', '投递企业安全研究院和大厂安全团队'],
    nextActions: ['选择一个 AI 安全落地场景', '把实验结果转成可演示 Demo', '准备研究与工程两套面试叙事'],
    risks: ['路线要求高', '需要持续输出', '要避免研究和工程都浅尝辄止'],
  },
];

const DEFAULT_RESUME = `网络空间安全本科生，熟悉 Python、Linux、Web 安全基础，参与过 CTF、漏洞复现和安全工具开发。

项目经历：
1. Web 漏洞扫描辅助工具：负责爬虫、指纹识别和 SQL 注入检测模块，完成 20 个靶场案例验证。
2. LLM 安全评测小实验：整理 Prompt Injection 样例，完成基础攻击样本分类和人工评估。
3. 校园安全运营实践：参与日志分析和弱口令排查，输出整改建议报告。`;

export function createDefaultWorkbench(): CareerWorkbench {
  const now = new Date().toISOString();
  return {
    id: 'careers-workbench-demo',
    selectedJobId: 'job-ai-research',
    selectedDirection: '全部',
    selectedCity: '全部',
    selectedCompanyId: 'company-bytedance',
    userSkills: DEFAULT_USER_SKILLS.map((skill) => ({ ...skill })),
    resumeDraft: DEFAULT_RESUME,
    resumeReviews: [],
    favoriteJobs: ['job-ai-research'],
    favoriteCompanies: ['company-bytedance'],
    comparedCompanyIds: [],
    learningPath: DEFAULT_LEARNING_PATH.map((item) => ({ ...item, relatedSkills: [...item.relatedSkills], resources: [...item.resources], tasks: [...item.tasks] })),
    learningProgress: {},
    learningPace: '标准',
    interviewProgress: {},
    directionPlans: DEFAULT_DIRECTION_PLANS.map((plan) => ({
      ...plan,
      milestones: [...plan.milestones],
      nextActions: [...plan.nextActions],
      risks: [...plan.risks],
    })),
    autosaveStatus: 'saved',
    savedAt: now,
    updatedAt: now,
  };
}
