import type {
  ForumComment,
  ForumNotice,
  ForumPost,
  ForumTopic,
  ForumUser,
  ForumWorkspace,
  QaQuestion,
  ResourceExchange,
  TeamRecruitment,
} from './types';

export const FORUM_STORAGE_KEY = 'forum-workspace-demo';

export const FORUM_TAGS = [
  '全部',
  'AI 安全',
  '红队',
  '蓝队',
  '竞赛',
  '面试',
  '论文',
  '工具',
  '零信任',
  '工控安全',
] as const;

export const EXPERIENCE_TAGS = ['全部', '竞赛经验', '科研经验', '就业经验', '保研经验', '护网实战'] as const;
export const RESOURCE_CATEGORIES = ['全部', '资料', '工具', '数据集', '算力', '经验'] as const;
export const TEAM_PROJECT_TYPES = ['全部', '挑战杯', '信安赛', '开源项目', '大创', '科研项目'] as const;

const USERS: ForumUser[] = [
  {
    id: 'user-current',
    name: '陈同学',
    avatarText: '陈',
    role: '网络空间安全本科生',
    school: '北京邮电大学',
    reputation: 860,
    postCount: 18,
    badges: ['蓝队值守', 'AI 安全实验'],
    activeDays: 42,
  },
  {
    id: 'user-kai',
    name: 'Kai',
    avatarText: 'K',
    role: '红队方向研究生',
    school: '北京邮电大学',
    reputation: 1280,
    postCount: 230,
    badges: ['内网渗透', '精华作者'],
    activeDays: 126,
  },
  {
    id: 'user-lin',
    name: '林同学',
    avatarText: '林',
    role: '竞赛队队长',
    school: '北京邮电大学',
    reputation: 980,
    postCount: 120,
    badges: ['信安赛', '经验分享'],
    activeDays: 88,
  },
  {
    id: 'user-amy',
    name: 'Amy',
    avatarText: 'A',
    role: '安全开发实习生',
    school: '北京邮电大学',
    reputation: 760,
    postCount: 64,
    badges: ['校招面经', '工具开发'],
    activeDays: 53,
  },
  {
    id: 'user-blue',
    name: '安枢小编',
    avatarText: '安',
    role: '社区运营',
    school: 'CyberLadder',
    reputation: 1120,
    postCount: 198,
    badges: ['活动组织', '资料整理'],
    activeDays: 210,
  },
];

function comment(
  id: string,
  postId: string,
  authorId: string,
  authorName: string,
  content: string,
  createdAt: string,
  likeCount = 0,
): ForumComment {
  return { id, postId, authorId, authorName, content, likeCount, liked: false, createdAt };
}

const POSTS: ForumPost[] = [
  {
    id: 'post-llm-jailbreak',
    board: 'security',
    title: 'LLM 越狱攻击防御思路：从输入隔离到工具权限收敛',
    authorId: 'user-kai',
    authorName: 'Kai',
    content:
      '最近在做 LLM Agent 安全评估，发现传统关键词过滤很难覆盖 Prompt Injection、角色覆盖和工具误调用。我的实践路径是先做上下文分层，把系统指令、用户输入、检索内容和工具返回分开标记；再给高危工具增加显式确认和最小权限；最后用越狱样本集做回归测试。欢迎补充你们在比赛或项目中的评估指标。',
    excerpt: '围绕 Prompt Injection、工具调用和上下文分层，总结 LLM 越狱攻击的前端演示级防御路线。',
    tags: ['AI 安全', '论文', '工具'],
    topicId: 'topic-ai-security',
    replyCount: 2,
    viewCount: 1204,
    likeCount: 46,
    favoriteCount: 18,
    liked: false,
    favorited: false,
    pinned: true,
    essence: true,
    createdAt: '2026-04-24T09:20:00.000+08:00',
    updatedAt: '2026-04-24T09:20:00.000+08:00',
    comments: [
      comment('comment-llm-1', 'post-llm-jailbreak', 'user-amy', 'Amy', '工具调用最好加审计日志，答辩时也能展示风险闭环。', '2026-04-24T10:12:00.000+08:00', 6),
      comment('comment-llm-2', 'post-llm-jailbreak', 'user-lin', '林同学', '可以补一个 jailbreak bench 的对照表，方便比较防护前后效果。', '2026-04-24T13:45:00.000+08:00', 3),
    ],
  },
  {
    id: 'post-bluehat',
    board: 'security',
    title: '蓝帽杯备赛经验：三周冲刺如何安排 Web / Misc / Crypto',
    authorId: 'user-lin',
    authorName: '林同学',
    content:
      '我们队今年把三周分成基础复盘、专项突破和模拟赛三段。第一周整理常见 Web 漏洞链和流量分析题，第二周做往年题并把脚本沉淀到仓库，第三周只打限时赛和复盘错题。最重要的是题解要统一模板，方便队友接手。',
    excerpt: '从任务拆分、题解模板到复盘节奏，记录蓝帽杯冲刺阶段的队伍协作方式。',
    tags: ['竞赛', '红队', '工具'],
    topicId: 'topic-contest',
    replyCount: 18,
    viewCount: 876,
    likeCount: 31,
    favoriteCount: 22,
    liked: false,
    favorited: false,
    pinned: false,
    essence: true,
    createdAt: '2026-04-22T21:10:00.000+08:00',
    updatedAt: '2026-04-22T21:10:00.000+08:00',
    comments: [
      comment('comment-bluehat-1', 'post-bluehat', 'user-current', '陈同学', '题解模板这点很有用，之前我们复盘成本太高。', '2026-04-23T08:20:00.000+08:00', 2),
    ],
  },
  {
    id: 'post-bloodhound',
    board: 'security',
    title: 'BloodHound 内网分析经验：从图谱路径到修复建议',
    authorId: 'user-kai',
    authorName: 'Kai',
    content:
      'BloodHound 不只是找最短路径。真实项目里更需要把高危 ACL、弱口令资产和敏感组权限串起来，最后输出能被蓝队执行的修复建议。我的做法是给路径按影响面、可利用性和修复成本打分，然后把高分路径转成加固清单。',
    excerpt: '分享 BloodHound 图谱分析、路径评分和蓝队修复清单的实战做法。',
    tags: ['红队', '蓝队', '工具'],
    topicId: 'topic-red-blue',
    replyCount: 41,
    viewCount: 2301,
    likeCount: 72,
    favoriteCount: 39,
    liked: false,
    favorited: false,
    pinned: false,
    essence: true,
    createdAt: '2026-04-18T16:40:00.000+08:00',
    updatedAt: '2026-04-18T16:40:00.000+08:00',
    comments: [
      comment('comment-bh-1', 'post-bloodhound', 'user-blue', '安枢小编', '可以考虑把评分表整理成资源交换区模板。', '2026-04-18T18:10:00.000+08:00', 5),
    ],
  },
  {
    id: 'post-zero-trust-books',
    board: 'security',
    title: '零信任方向入门书单：从身份治理到访问代理',
    authorId: 'user-current',
    authorName: '陈同学',
    content:
      '我在准备挑战杯零信任项目，整理了一条入门路径：先看 NIST SP 800-207 理解原则，再补 IAM、设备可信、访问代理和策略引擎。项目展示时可以用校园网资源访问场景，把“持续验证”和“最小权限”讲清楚。',
    excerpt: '给零信任初学者的一份书单和落地场景拆解，适合竞赛项目选题。',
    tags: ['零信任', '竞赛', '论文'],
    topicId: 'topic-zero-trust',
    replyCount: 12,
    viewCount: 233,
    likeCount: 19,
    favoriteCount: 11,
    liked: false,
    favorited: false,
    pinned: false,
    essence: false,
    createdAt: '2026-04-20T11:05:00.000+08:00',
    updatedAt: '2026-04-20T11:05:00.000+08:00',
    comments: [],
  },
  {
    id: 'post-ics-tools',
    board: 'security',
    title: '工控协议安全测试工具推荐：Modbus、OPC UA 与流量回放',
    authorId: 'user-blue',
    authorName: '安枢小编',
    content:
      '工控安全入门建议先搭小型仿真环境，工具可以从 Wireshark、mbtget、OpenPLC、Scapy 和 Zeek 规则开始。不要直接碰真实生产系统，答辩演示可以用离线 pcap 和本地仿真设备展示风险点。',
    excerpt: '整理工控协议学习和安全测试常用工具，并给出离线演示建议。',
    tags: ['工控安全', '工具', '蓝队'],
    topicId: 'topic-ics',
    replyCount: 15,
    viewCount: 944,
    likeCount: 38,
    favoriteCount: 27,
    liked: false,
    favorited: false,
    pinned: false,
    essence: false,
    createdAt: '2026-04-19T14:25:00.000+08:00',
    updatedAt: '2026-04-19T14:25:00.000+08:00',
    comments: [],
  },
  {
    id: 'post-fgsm-pgd',
    board: 'security',
    title: 'PGD / FGSM 对抗样本复现实验：从 CIFAR-10 到防御评估',
    authorId: 'user-amy',
    authorName: 'Amy',
    content:
      '复现 FGSM 和 PGD 时最容易忽略归一化、epsilon 尺度和随机种子。建议先固定模型和数据集，再对比 clean accuracy、attack success rate 和鲁棒准确率。报告里把扰动可视化和指标表放在一起，老师更容易理解。',
    excerpt: '记录对抗样本复现实验中的参数陷阱、指标设计和可视化展示方式。',
    tags: ['AI 安全', '论文', '竞赛'],
    topicId: 'topic-ai-security',
    replyCount: 9,
    viewCount: 621,
    likeCount: 25,
    favoriteCount: 16,
    liked: false,
    favorited: false,
    pinned: false,
    essence: false,
    createdAt: '2026-04-16T20:30:00.000+08:00',
    updatedAt: '2026-04-16T20:30:00.000+08:00',
    comments: [],
  },
  {
    id: 'post-snort-suricata',
    board: 'exp',
    title: 'Snort / Suricata 规则编写经验：从误报治理到护网复盘',
    authorId: 'user-blue',
    authorName: '安枢小编',
    content:
      '写规则不要只追求命中率，误报治理同样重要。我的习惯是先用 pcap 还原攻击链，再把规则拆成协议字段、关键载荷和上下文条件。护网复盘时，把规则版本、命中样本和误报样本一起归档，后续迭代会快很多。',
    excerpt: '分享 IDS 规则编写和护网复盘中的误报治理方法。',
    tags: ['护网实战', '蓝队', '工具'],
    topicId: 'topic-open-tools',
    replyCount: 33,
    viewCount: 1980,
    likeCount: 58,
    favoriteCount: 34,
    liked: false,
    favorited: false,
    pinned: true,
    essence: true,
    createdAt: '2026-04-14T10:00:00.000+08:00',
    updatedAt: '2026-04-14T10:00:00.000+08:00',
    comments: [
      comment('comment-snort-1', 'post-snort-suricata', 'user-kai', 'Kai', '建议补充 rule sid 管理规范，团队协作时很关键。', '2026-04-14T11:30:00.000+08:00', 4),
    ],
  },
  {
    id: 'post-optee-qemu',
    board: 'exp',
    title: 'OP-TEE / QEMU 实验踩坑总结：环境版本比命令更重要',
    authorId: 'user-current',
    authorName: '陈同学',
    content:
      'OP-TEE 环境最容易卡在 repo 版本、交叉编译器和 QEMU 参数不匹配。建议把 Ubuntu 版本、manifest、gcc 版本和启动命令都写进 README。遇到 hang 住时先看串口日志，再排查 secure world 是否正常启动。',
    excerpt: '整理可信执行环境实验中 repo、编译器、QEMU 参数和串口日志排错经验。',
    tags: ['科研经验', '工具', '论文'],
    topicId: 'topic-paper',
    replyCount: 21,
    viewCount: 1308,
    likeCount: 44,
    favoriteCount: 29,
    liked: false,
    favorited: false,
    pinned: false,
    essence: true,
    createdAt: '2026-04-12T19:20:00.000+08:00',
    updatedAt: '2026-04-12T19:20:00.000+08:00',
    comments: [],
  },
  {
    id: 'post-job-security-dev',
    board: 'exp',
    title: '从零到安全开发实习：我的 2 年学习路线复盘',
    authorId: 'user-amy',
    authorName: 'Amy',
    content:
      '安全开发岗位既看安全基础，也看工程能力。我前期用 Python 写漏洞复现脚本，中期补 Go、Linux 和网络协议，后期把工具做成可演示项目。面试时项目的输入输出、性能边界和安全收益要说清楚。',
    excerpt: '从 Web 安全、工程能力到简历项目，复盘安全开发实习准备路径。',
    tags: ['就业经验', '面试', '工具'],
    topicId: 'topic-interview',
    replyCount: 57,
    viewCount: 3211,
    likeCount: 88,
    favoriteCount: 52,
    liked: false,
    favorited: false,
    pinned: false,
    essence: true,
    createdAt: '2026-04-10T09:50:00.000+08:00',
    updatedAt: '2026-04-10T09:50:00.000+08:00',
    comments: [],
  },
];

const TOPICS: ForumTopic[] = [
  {
    id: 'topic-ai-security',
    title: 'AI 安全',
    summary: '围绕 LLM 越狱、对抗样本、模型评测和智能体安全展开讨论。',
    tags: ['AI 安全', '论文', '工具'],
    discussionCount: 128,
    heatScore: 96,
    followed: false,
    relatedPostIds: ['post-llm-jailbreak', 'post-fgsm-pgd'],
  },
  {
    id: 'topic-red-blue',
    title: '红蓝对抗',
    summary: '攻防演练、内网路径分析、告警研判和复盘报告模板。',
    tags: ['红队', '蓝队'],
    discussionCount: 112,
    heatScore: 91,
    followed: true,
    relatedPostIds: ['post-bloodhound'],
  },
  {
    id: 'topic-contest',
    title: '竞赛交流',
    summary: '信安赛、蓝帽杯、强网杯和挑战杯的备赛经验与组队协作。',
    tags: ['竞赛', '经验'],
    discussionCount: 89,
    heatScore: 88,
    followed: false,
    relatedPostIds: ['post-bluehat'],
  },
  {
    id: 'topic-interview',
    title: '面试面经',
    summary: '安全开发、渗透测试、安全运营等方向的简历和面试复盘。',
    tags: ['面试', '就业经验'],
    discussionCount: 74,
    heatScore: 81,
    followed: false,
    relatedPostIds: ['post-job-security-dev'],
  },
  {
    id: 'topic-open-tools',
    title: '开源工具',
    summary: '分享自研工具、规则模板、复现实验脚本和开源协作经验。',
    tags: ['工具', '蓝队'],
    discussionCount: 65,
    heatScore: 78,
    followed: false,
    relatedPostIds: ['post-snort-suricata'],
  },
  {
    id: 'topic-zero-trust',
    title: '零信任',
    summary: '身份治理、设备可信、访问代理和策略引擎的学习与项目落地。',
    tags: ['零信任', '竞赛'],
    discussionCount: 54,
    heatScore: 72,
    followed: false,
    relatedPostIds: ['post-zero-trust-books'],
  },
  {
    id: 'topic-ics',
    title: '工控安全',
    summary: '工控协议、仿真环境、离线流量分析和安全测试工具。',
    tags: ['工控安全', '工具'],
    discussionCount: 43,
    heatScore: 68,
    followed: false,
    relatedPostIds: ['post-ics-tools'],
  },
  {
    id: 'topic-paper',
    title: '科研论文',
    summary: '论文精读、复现实验、实验环境和科研写作经验。',
    tags: ['论文', '科研经验'],
    discussionCount: 61,
    heatScore: 70,
    followed: false,
    relatedPostIds: ['post-optee-qemu'],
  },
];

const TEAMS: TeamRecruitment[] = [
  {
    id: 'team-zero-trust',
    title: '挑战杯零信任工业互联网项目',
    projectType: '挑战杯',
    direction: '零信任 / 工控安全',
    description:
      '围绕工业互联网远程运维场景，设计零信任访问代理、设备可信评估和安全审计闭环，目标是完成可演示原型和项目书。',
    requiredRoles: ['前端可视化', '后端网关', '安全方案撰写'],
    currentMembers: ['林同学', '陈同学'],
    maxMembers: 5,
    ownerId: 'user-lin',
    ownerName: '林同学',
    tags: ['零信任', '工控安全', '挑战杯'],
    status: '招募中',
    applied: false,
    applicationRequirement: '请说明你熟悉的技术栈、可投入时间和希望负责的模块。',
    contactHint: '申请通过后会在站内显示负责人微信，演示环境使用 mock 文案。',
    createdAt: '2026-04-21T12:00:00.000+08:00',
  },
  {
    id: 'team-ctf',
    title: '信息安全竞赛 Web / Pwn / Misc 队伍',
    projectType: '信安赛',
    direction: 'CTF 综合能力',
    description:
      '面向大学生信息安全竞赛，队伍已有 Web 和 Crypto 基础，希望补 Pwn 和 Misc 方向，统一维护题解仓库。',
    requiredRoles: ['Pwn 方向', 'Misc 方向', '赛后复盘整理'],
    currentMembers: ['Kai', '林同学', 'Amy'],
    maxMembers: 5,
    ownerId: 'user-kai',
    ownerName: 'Kai',
    tags: ['竞赛', '红队', '题解'],
    status: '招募中',
    applied: false,
    applicationRequirement: '附上最近做过的题目类型和每周训练时间。',
    contactHint: '通过申请后加入训练群，演示阶段不展示真实联系方式。',
    createdAt: '2026-04-19T15:20:00.000+08:00',
  },
  {
    id: 'team-ai-tool',
    title: 'AI 安全评估工具开源项目',
    projectType: '开源项目',
    direction: 'LLM 安全 / 评测平台',
    description:
      '构建 Prompt Injection 样本管理、自动化评测和报告生成工具，适合想积累开源项目和论文复现实验的同学。',
    requiredRoles: ['PyTorch / Python', '前端仪表盘', '测试样本整理'],
    currentMembers: ['Amy'],
    maxMembers: 4,
    ownerId: 'user-amy',
    ownerName: 'Amy',
    tags: ['AI 安全', '开源工具', '论文'],
    status: '招募中',
    applied: false,
    applicationRequirement: '请说明你是否做过模型评测或 Web 工具开发。',
    contactHint: '申请通过后会同步 GitHub 仓库邀请，当前为演示模拟。',
    createdAt: '2026-04-17T20:30:00.000+08:00',
  },
  {
    id: 'team-privacy',
    title: '隐私计算大创项目',
    projectType: '大创',
    direction: '隐私计算 / 医疗数据',
    description:
      '研究联邦学习和隐私保护数据分析在医疗场景中的应用，已有指导老师资源，需要补实验和文档同学。',
    requiredRoles: ['联邦学习实验', '文献综述', '项目书排版'],
    currentMembers: ['安枢小编', '陈同学', '林同学'],
    maxMembers: 4,
    ownerId: 'user-blue',
    ownerName: '安枢小编',
    tags: ['科研项目', '论文', '数据集'],
    status: '招募中',
    applied: false,
    applicationRequirement: '请说明数学基础、论文阅读经验和可承担任务。',
    contactHint: '通过申请后由负责人拉入项目群，联系方式为 mock。',
    createdAt: '2026-04-15T08:40:00.000+08:00',
  },
  {
    id: 'team-hvv-blue',
    title: '护网蓝队实训小组',
    projectType: '科研项目',
    direction: '蓝队值守 / 告警研判',
    description:
      '以校园靶场流量为样本，练习告警研判、规则调优、日报撰写和复盘材料沉淀。',
    requiredRoles: ['告警分析', '规则调优'],
    currentMembers: ['Kai', '安枢小编', 'Amy', '林同学'],
    maxMembers: 4,
    ownerId: 'user-blue',
    ownerName: '安枢小编',
    tags: ['护网实战', '蓝队'],
    status: '已满员',
    applied: false,
    applicationRequirement: '满员项目暂不接收申请，可收藏后关注后续开放。',
    contactHint: '满员状态下不展示联系方式。',
    createdAt: '2026-04-12T13:00:00.000+08:00',
  },
];

const QUESTIONS: QaQuestion[] = [
  {
    id: 'qa-web-pwn',
    title: 'Web 学完后选 Pwn 还是逆向？',
    content: '已经做过 SQL 注入、XSS、文件上传和简单 SSRF，想参加综合 CTF。下一步应该转 Pwn 还是逆向？希望有路线建议。',
    authorId: 'user-current',
    authorName: '陈同学',
    tags: ['竞赛', '红队'],
    status: '待解决',
    answerCount: 1,
    viewCount: 356,
    favorited: false,
    createdAt: '2026-04-23T15:00:00.000+08:00',
    answers: [
      {
        id: 'answer-web-pwn-1',
        questionId: 'qa-web-pwn',
        authorId: 'user-kai',
        authorName: 'Kai',
        content: '如果目标是信安赛综合队，建议先补 Linux、汇编和 pwntools，Pwn 入门收益更直接；逆向可以同步用基础题保持手感。',
        likeCount: 8,
        liked: false,
        accepted: false,
        createdAt: '2026-04-23T16:10:00.000+08:00',
      },
    ],
  },
  {
    id: 'qa-log4shell',
    title: '怎样复现 Log4Shell 比较稳？',
    content: '想在本地搭一个安全的 Log4Shell 复现实验，避免依赖不稳定镜像。有哪些版本和网络隔离注意点？',
    authorId: 'user-lin',
    authorName: '林同学',
    tags: ['Web 安全', '漏洞复现'],
    status: '已解决',
    answerCount: 2,
    viewCount: 880,
    favorited: false,
    acceptedAnswerId: 'answer-log4shell-1',
    createdAt: '2026-04-19T18:00:00.000+08:00',
    answers: [
      {
        id: 'answer-log4shell-1',
        questionId: 'qa-log4shell',
        authorId: 'user-blue',
        authorName: '安枢小编',
        content: '用固定版本的 vulnerable app 和本地 LDAP/RMI mock 服务即可，环境放在隔离 Docker 网络里，复现后立刻清理容器和镜像。',
        likeCount: 18,
        liked: false,
        accepted: true,
        createdAt: '2026-04-19T19:20:00.000+08:00',
      },
      {
        id: 'answer-log4shell-2',
        questionId: 'qa-log4shell',
        authorId: 'user-amy',
        authorName: 'Amy',
        content: '报告里记得写清楚 JDK 版本差异，否则复现实验很容易前后不一致。',
        likeCount: 5,
        liked: false,
        accepted: false,
        createdAt: '2026-04-20T09:40:00.000+08:00',
      },
    ],
  },
  {
    id: 'qa-security-dev',
    title: '校招安全开发要补什么？',
    content: '会 Python 和 Web 安全，想投安全开发。Go、K8s、SAST、eBPF 哪个优先级更高？',
    authorId: 'user-amy',
    authorName: 'Amy',
    tags: ['面试', '就业经验'],
    status: '已解决',
    answerCount: 1,
    viewCount: 960,
    favorited: false,
    acceptedAnswerId: 'answer-dev-1',
    createdAt: '2026-04-17T20:10:00.000+08:00',
    answers: [
      {
        id: 'answer-dev-1',
        questionId: 'qa-security-dev',
        authorId: 'user-kai',
        authorName: 'Kai',
        content: '先补 Go、Linux 网络和一个可演示工具项目。K8s/eBPF 是加分项，除非岗位明确要求，否则不要分散主线。',
        likeCount: 14,
        liked: false,
        accepted: true,
        createdAt: '2026-04-18T08:20:00.000+08:00',
      },
    ],
  },
  {
    id: 'qa-paper-rewrite',
    title: '论文降重是否有靠谱工具？',
    content: '课程论文查重偏高，想知道有没有靠谱工具或流程，避免只做机械替换。',
    authorId: 'user-current',
    authorName: '陈同学',
    tags: ['论文', '科研经验'],
    status: '待解决',
    answerCount: 0,
    viewCount: 210,
    favorited: false,
    createdAt: '2026-04-22T11:30:00.000+08:00',
    answers: [],
  },
  {
    id: 'qa-optee-qemu',
    title: 'WSL2 下 OP-TEE / QEMU 如何排错？',
    content: '在 WSL2 编译 OP-TEE 可以过，但启动 QEMU 后串口没输出。应该从哪里开始查？',
    authorId: 'user-lin',
    authorName: '林同学',
    tags: ['科研经验', '工具'],
    status: '待解决',
    answerCount: 1,
    viewCount: 430,
    favorited: false,
    createdAt: '2026-04-21T21:30:00.000+08:00',
    answers: [
      {
        id: 'answer-optee-1',
        questionId: 'qa-optee-qemu',
        authorId: 'user-current',
        authorName: '陈同学',
        content: '先确认 manifest、toolchain 和 QEMU 版本，启动命令加串口输出参数；如果 secure world 没起来，普通世界日志会很少。',
        likeCount: 4,
        liked: false,
        accepted: false,
        createdAt: '2026-04-22T08:00:00.000+08:00',
      },
    ],
  },
  {
    id: 'qa-snort-debug',
    title: 'Snort 规则如何调试？',
    content: '写了几条规则但误报很多，想知道调试和版本管理有没有推荐流程。',
    authorId: 'user-blue',
    authorName: '安枢小编',
    tags: ['蓝队', '工具'],
    status: '待解决',
    answerCount: 0,
    viewCount: 188,
    favorited: false,
    createdAt: '2026-04-20T14:45:00.000+08:00',
    answers: [],
  },
];

const NOTICES: ForumNotice[] = [
  {
    id: 'notice-star',
    title: '论坛之星评选结果公示',
    type: '官方',
    content: '本月论坛之星将根据精华帖、优质回答、资源贡献和活动参与度综合评选。欢迎在公示期内反馈。',
    date: '2026-04-27 19:00',
    location: '线上社区直播间',
    organizer: 'CyberLadder 社区运营组',
    registered: false,
    reminded: false,
    tags: ['社区', '评选'],
  },
  {
    id: 'notice-zero-trust-class',
    title: '零信任实战公开课',
    type: '讲座',
    content: '课程将以校园资源访问和工业互联网远程运维两个场景，拆解身份治理、访问代理、策略引擎和审计闭环。',
    date: '2026-04-28 20:00',
    location: '腾讯会议 / 教三 305',
    organizer: '安全研究院合作讲师',
    registered: false,
    reminded: false,
    tags: ['零信任', '讲座'],
  },
  {
    id: 'notice-qwb',
    title: '强网杯报名提醒',
    type: '赛事',
    content: '强网杯青少年专项赛开放报名，请参赛同学提前确认队伍信息、指导老师和报名材料。',
    date: '2026-05-01 12:00',
    location: '赛事官网',
    organizer: '竞赛服务中心',
    registered: false,
    reminded: false,
    tags: ['竞赛', '报名'],
  },
  {
    id: 'notice-ai-paper',
    title: 'AI 安全论文精读活动',
    type: '活动',
    content: '本期共读 Prompt Injection 和对抗样本方向论文，参与者需提前提交一页阅读笔记。',
    date: '2026-05-04 19:30',
    location: '图书馆研讨间 B210',
    organizer: 'AI 安全兴趣小组',
    registered: false,
    reminded: false,
    tags: ['AI 安全', '论文'],
  },
  {
    id: 'notice-hvv-share',
    title: '护网经验分享会',
    type: '合作',
    content: '邀请企业蓝队工程师分享告警研判、值守协作、日报撰写和复盘材料沉淀。',
    date: '2026-05-08 18:30',
    location: '教四 201',
    organizer: '校企合作中心',
    registered: false,
    reminded: false,
    tags: ['护网实战', '蓝队'],
  },
];

const RESOURCES: ResourceExchange[] = [
  {
    id: 'resource-zero-trust',
    title: '零信任白皮书合集',
    offered: 'NIST、国内标准解读和项目书参考框架',
    wanted: '工业互联网安全标准汇编或案例报告',
    ownerId: 'user-current',
    ownerName: '陈同学',
    description: '适合挑战杯和课程汇报引用，已按身份、设备、网络、审计四类整理。',
    category: '资料',
    tags: ['零信任', '资料'],
    status: '可交换',
    favorited: false,
    exchangeRequested: false,
    createdAt: '2026-04-21T17:00:00.000+08:00',
  },
  {
    id: 'resource-ciscn',
    title: '大学生信安赛真题合集',
    offered: '近三年 Web / Pwn / Misc 真题与部分题解',
    wanted: '蓝帽杯或强网杯题解 Wiki',
    ownerId: 'user-lin',
    ownerName: '林同学',
    description: '按题型和知识点标注，适合队伍训练和赛前复盘。',
    category: '资料',
    tags: ['竞赛', '题解'],
    status: '可交换',
    favorited: false,
    exchangeRequested: false,
    createdAt: '2026-04-20T10:30:00.000+08:00',
  },
  {
    id: 'resource-ctf-wiki',
    title: 'CTF 题解 Wiki',
    offered: 'Web、Crypto、Misc 题解模板和复盘规范',
    wanted: 'Pwn 入门训练计划',
    ownerId: 'user-kai',
    ownerName: 'Kai',
    description: '团队内部使用过的 Wiki 结构，已脱敏，适合快速建立题解仓库。',
    category: '经验',
    tags: ['竞赛', '经验'],
    status: '可交换',
    favorited: false,
    exchangeRequested: false,
    createdAt: '2026-04-18T11:15:00.000+08:00',
  },
  {
    id: 'resource-intranet',
    title: '内网渗透笔记',
    offered: 'BloodHound、Kerberoasting、横向移动防护视角笔记',
    wanted: '蓝队检测规则或日志样本',
    ownerId: 'user-kai',
    ownerName: 'Kai',
    description: '强调合法靶场和防护视角，适合红蓝对抗学习。',
    category: '资料',
    tags: ['红队', '蓝队'],
    status: '可交换',
    favorited: false,
    exchangeRequested: false,
    createdAt: '2026-04-17T09:40:00.000+08:00',
  },
  {
    id: 'resource-ai-paper',
    title: 'AI 安全论文复现集',
    offered: 'FGSM / PGD、Prompt Injection 样本和实验 README',
    wanted: 'GPU 算力时段或模型评测脚本',
    ownerId: 'user-amy',
    ownerName: 'Amy',
    description: '包含可复现实验参数和指标说明，方便科研训练或展示。',
    category: '数据集',
    tags: ['AI 安全', '论文'],
    status: '可交换',
    favorited: false,
    exchangeRequested: false,
    createdAt: '2026-04-16T16:20:00.000+08:00',
  },
  {
    id: 'resource-optee',
    title: 'OP-TEE 实验环境配置清单',
    offered: 'Ubuntu、manifest、toolchain、QEMU 命令和排错清单',
    wanted: '可信执行环境论文精读笔记',
    ownerId: 'user-current',
    ownerName: '陈同学',
    description: '适合 WSL2 或 Linux 虚拟机复现实验，已记录常见失败点。',
    category: '工具',
    tags: ['科研经验', '工具'],
    status: '可交换',
    favorited: false,
    exchangeRequested: false,
    createdAt: '2026-04-15T21:00:00.000+08:00',
  },
];

function clonePost(post: ForumPost): ForumPost {
  return {
    ...post,
    tags: [...post.tags],
    comments: post.comments.map((item) => ({ ...item })),
  };
}

function cloneQuestion(question: QaQuestion): QaQuestion {
  return {
    ...question,
    tags: [...question.tags],
    answers: question.answers.map((answer) => ({ ...answer })),
  };
}

export function createDefaultForumWorkspace(): ForumWorkspace {
  const now = new Date().toISOString();
  return {
    id: 'forum-workspace-demo',
    activeBoard: 'security',
    activeTopicId: undefined,
    searchQuery: '',
    selectedTag: '全部',
    sortBy: 'latest',
    currentUser: { ...USERS[0], badges: [...USERS[0].badges] },
    users: USERS.map((user) => ({ ...user, badges: [...user.badges] })),
    posts: POSTS.map(clonePost),
    topics: TOPICS.map((topic) => ({
      ...topic,
      tags: [...topic.tags],
      relatedPostIds: [...topic.relatedPostIds],
    })),
    teams: TEAMS.map((team) => ({
      ...team,
      tags: [...team.tags],
      requiredRoles: [...team.requiredRoles],
      currentMembers: [...team.currentMembers],
    })),
    questions: QUESTIONS.map(cloneQuestion),
    notices: NOTICES.map((notice) => ({ ...notice, tags: [...notice.tags] })),
    resources: RESOURCES.map((resource) => ({ ...resource, tags: [...resource.tags] })),
    drafts: [],
    likedPostIds: [],
    favoritePostIds: [],
    favoriteQuestionIds: [],
    favoriteResourceIds: [],
    joinedTeamIds: [],
    noticeRegistrationIds: [],
    exchangeRecords: [],
    autosaveStatus: 'saved',
    savedAt: now,
    updatedAt: now,
  };
}
