import type { Milestone, TaskActivity, TaskFilters, TaskItem, TaskStatus, TaskWorkbench, TeamMember } from './types';
import { addDays, monthIso, taskStatusOrder } from './utils';

export const TASKS_STORAGE_KEY = 'tasks-workbench-demo';

const nowIso = () => new Date().toISOString();

export const defaultFilters: TaskFilters = {
  query: '',
  status: 'all',
  priority: 'all',
  module: 'all',
  assigneeId: 'all',
  milestoneId: 'all',
  dateRange: 'all',
  showArchived: false,
};

export function createDefaultTeamMembers(): TeamMember[] {
  return [
    {
      id: 'member-chen',
      name: '陈同学',
      role: '队长 / 写作 / 统筹',
      avatarText: '陈',
      capacityHoursPerWeek: 28,
      skillTags: ['写作', '统筹', '答辩'],
      currentLoadHours: 0,
      assignedTaskIds: [],
    },
    {
      id: 'member-li',
      name: '李同学',
      role: '实验 / 算法',
      avatarText: '李',
      capacityHoursPerWeek: 24,
      skillTags: ['实验', '算法', '复现'],
      currentLoadHours: 0,
      assignedTaskIds: [],
    },
    {
      id: 'member-wang',
      name: '王同学',
      role: '工程 / 后端',
      avatarText: '王',
      capacityHoursPerWeek: 22,
      skillTags: ['工程', '后端', '安全工具'],
      currentLoadHours: 0,
      assignedTaskIds: [],
    },
    {
      id: 'member-zhao',
      name: '赵同学',
      role: '设计 / PPT',
      avatarText: '赵',
      capacityHoursPerWeek: 18,
      skillTags: ['PPT', '设计', '演示'],
      currentLoadHours: 0,
      assignedTaskIds: [],
    },
    {
      id: 'member-liu',
      name: '刘同学',
      role: '资料 / 调研',
      avatarText: '刘',
      capacityHoursPerWeek: 16,
      skillTags: ['资料', '政策', '文献'],
      currentLoadHours: 0,
      assignedTaskIds: [],
    },
  ];
}

function createDefaultMilestones(): Milestone[] {
  return [
    {
      id: 'ms-topic',
      title: '选题通过',
      description: '确认挑战杯选题、核心场景和导师反馈。',
      targetDate: addDays(-12),
      status: 'completed',
      relatedTaskIds: ['task-zero-trust-topic', 'task-mentor-plan'],
      deliverables: ['选题推演结论', '导师确认记录'],
      riskLevel: 'low',
      ownerId: 'member-chen',
    },
    {
      id: 'ms-literature',
      title: '论文综述定稿',
      description: '完成零信任、AI 安全和供应链安全文献综述。',
      targetDate: addDays(4),
      status: 'at_risk',
      relatedTaskIds: ['task-zero-trust-literature', 'task-ai-paper-repro'],
      deliverables: ['综述 Markdown', '引用证据表'],
      riskLevel: 'high',
      ownerId: 'member-liu',
    },
    {
      id: 'ms-experiment',
      title: '实验结果达标',
      description: '完成 OP-TEE/QEMU、Snort 规则和基线实验结果。',
      targetDate: addDays(15),
      status: 'in_progress',
      relatedTaskIds: ['task-optee-log', 'task-snort-rule', 'task-log4shell'],
      deliverables: ['实验日志', '规则调试记录', '复现实验报告'],
      riskLevel: 'medium',
      ownerId: 'member-li',
    },
    {
      id: 'ms-prototype',
      title: '系统原型完成',
      description: '完成演示工作台和后端 scaffold 联调说明。',
      targetDate: addDays(22),
      status: 'in_progress',
      relatedTaskIds: ['task-canvas-fill', 'task-forum-team'],
      deliverables: ['前端演示原型', '接口说明'],
      riskLevel: 'medium',
      ownerId: 'member-wang',
    },
    {
      id: 'ms-submit',
      title: '提交国赛作品',
      description: '冻结计划书、作品说明书和提交材料。',
      targetDate: addDays(33),
      status: 'not_started',
      relatedTaskIds: ['task-proposal-section', 'task-policy-checklist'],
      deliverables: ['计划书终稿', '作品说明书', '证明材料'],
      riskLevel: 'medium',
      ownerId: 'member-chen',
    },
    {
      id: 'ms-defense',
      title: '答辩材料定稿',
      description: '完成 PPT、大纲、讲稿和演示路线。',
      targetDate: addDays(42),
      status: 'not_started',
      relatedTaskIds: ['task-ppt-review', 'task-job-report'],
      deliverables: ['答辩 PPT', '演示脚本', '问答清单'],
      riskLevel: 'low',
      ownerId: 'member-zhao',
    },
  ];
}

function task(overrides: Partial<TaskItem> & Pick<TaskItem, 'id' | 'title' | 'description' | 'status' | 'assigneeId' | 'startDate' | 'dueDate' | 'estimateHours'>): TaskItem {
  const createdAt = addDays(-7);
  return {
    priority: 'medium',
    module: 'manual',
    sourceLabel: '手动创建',
    sourcePath: '/tasks?tab=list',
    collaboratorIds: [],
    spentHours: 0,
    tags: [],
    milestoneId: undefined,
    evidenceIds: [],
    dependencyIds: [],
    comments: [],
    createdAt,
    updatedAt: nowIso(),
    archived: false,
    ...overrides,
    completedAt: overrides.status === 'done' ? nowIso() : overrides.completedAt,
  };
}

function createDefaultTasks(): TaskItem[] {
  return [
    task({
      id: 'task-log4shell',
      title: '复现 Log4Shell 漏洞链路',
      description: '完成靶场复现、payload 记录、修复建议和截图证据整理。',
      status: 'todo',
      priority: 'high',
      module: 'practice',
      sourceLabel: '实战案例',
      sourcePath: '/practice?tab=cases',
      assigneeId: 'member-li',
      collaboratorIds: ['member-wang'],
      startDate: addDays(-1),
      dueDate: addDays(2),
      estimateHours: 6,
      spentHours: 1,
      tags: ['漏洞复现', 'Log4Shell'],
      milestoneId: 'ms-experiment',
      evidenceIds: ['ev-log4shell-lab'],
    }),
    task({
      id: 'task-zero-trust-literature',
      title: '收集零信任文献 10 篇',
      description: '筛选工业互联网、能源行业和关键信息基础设施相关零信任论文。',
      status: 'doing',
      priority: 'high',
      module: 'research',
      sourceLabel: '热点文章',
      sourcePath: '/research?tab=hot',
      assigneeId: 'member-liu',
      collaboratorIds: ['member-chen'],
      startDate: addDays(-4),
      dueDate: addDays(1),
      estimateHours: 8,
      spentHours: 4,
      tags: ['零信任', '文献'],
      milestoneId: 'ms-literature',
      evidenceIds: ['ev-zero-trust-paper'],
    }),
    task({
      id: 'task-mentor-plan',
      title: '和导师确认挑战杯技术方案',
      description: '确认技术路线、可行性、创新点和答辩表达边界。',
      status: 'done',
      priority: 'high',
      module: 'workspace',
      sourceLabel: '今日要务',
      sourcePath: '/workspace?tab=today',
      assigneeId: 'member-chen',
      startDate: addDays(-9),
      dueDate: addDays(-5),
      estimateHours: 2,
      spentHours: 2,
      tags: ['挑战杯', '导师反馈'],
      milestoneId: 'ms-topic',
      comments: [{ id: 'comment-mentor', author: '陈同学', content: '导师建议把应用场景收敛到工业互联网远程运维。', createdAt: nowIso() }],
    }),
    task({
      id: 'task-proposal-section',
      title: '完成计划书 3.2 节写作',
      description: '补齐创新点、技术方案和指标验证思路。',
      status: 'doing',
      priority: 'high',
      module: 'writing',
      sourceLabel: '计划书生成',
      sourcePath: '/writing?tab=proposal',
      assigneeId: 'member-chen',
      collaboratorIds: ['member-liu'],
      startDate: addDays(-2),
      dueDate: addDays(3),
      estimateHours: 5,
      spentHours: 2,
      tags: ['写作', '挑战杯'],
      milestoneId: 'ms-submit',
      evidenceIds: ['ev-policy-cii', 'ev-zero-trust-paper'],
    }),
    task({
      id: 'task-ai-paper-repro',
      title: 'AI 安全论文复现',
      description: '复现一篇 Agent 工具调用安全论文，整理攻击面和防护策略。',
      status: 'doing',
      priority: 'medium',
      module: 'research',
      sourceLabel: '论文精读',
      sourcePath: '/research?tab=hot',
      assigneeId: 'member-li',
      collaboratorIds: ['member-wang'],
      startDate: addDays(-5),
      dueDate: addDays(6),
      estimateHours: 10,
      spentHours: 3,
      tags: ['AI 安全', '论文复现'],
      milestoneId: 'ms-literature',
    }),
    task({
      id: 'task-job-report',
      title: '网安就业岗位分析报告',
      description: '更新安全运营工程师岗位画像、技能缺口和简历建议。',
      status: 'doing',
      priority: 'medium',
      module: 'careers',
      sourceLabel: '岗位分析',
      sourcePath: '/careers?tab=analysis',
      assigneeId: 'member-chen',
      collaboratorIds: ['member-liu'],
      startDate: addDays(-3),
      dueDate: addDays(5),
      estimateHours: 4,
      spentHours: 2,
      tags: ['就业', '岗位分析'],
      milestoneId: 'ms-defense',
    }),
    task({
      id: 'task-ppt-review',
      title: 'PPT 大纲 v2 评审',
      description: '检查答辩 PPT 结构、视觉密度、演示顺序和风险问答。',
      status: 'review',
      priority: 'medium',
      module: 'writing',
      sourceLabel: 'PPT 大纲',
      sourcePath: '/writing?tab=ppt',
      assigneeId: 'member-zhao',
      collaboratorIds: ['member-chen'],
      startDate: addDays(-1),
      dueDate: addDays(8),
      estimateHours: 3,
      spentHours: 2,
      tags: ['PPT', '答辩'],
      milestoneId: 'ms-defense',
    }),
    task({
      id: 'task-zero-trust-topic',
      title: '选题推演：零信任工业互联网',
      description: '完成选题推演卡、场景约束和项目价值论证。',
      status: 'done',
      priority: 'medium',
      module: 'writing',
      sourceLabel: '选题推演',
      sourcePath: '/writing?tab=deduce',
      assigneeId: 'member-chen',
      startDate: addDays(-18),
      dueDate: addDays(-13),
      estimateHours: 4,
      spentHours: 4,
      tags: ['零信任', '选题'],
      milestoneId: 'ms-topic',
    }),
    task({
      id: 'task-canvas-fill',
      title: '创意画布填充',
      description: '补齐用户、场景、解决方案、差异化价值和验证方式。',
      status: 'done',
      priority: 'low',
      module: 'writing',
      sourceLabel: '创意画布',
      sourcePath: '/writing?tab=canvas',
      assigneeId: 'member-chen',
      collaboratorIds: ['member-zhao'],
      startDate: addDays(-12),
      dueDate: addDays(-8),
      estimateHours: 3,
      spentHours: 3,
      tags: ['画布', '写作'],
      milestoneId: 'ms-prototype',
    }),
    task({
      id: 'task-optee-log',
      title: 'OP-TEE/QEMU 实验日志整理',
      description: '整理 QEMU 启动、TA 调用、异常日志和复现实验步骤。',
      status: 'todo',
      priority: 'high',
      module: 'research',
      sourceLabel: '开放实验室',
      sourcePath: '/research?tab=lab',
      assigneeId: 'member-wang',
      collaboratorIds: ['member-li'],
      startDate: addDays(0),
      dueDate: addDays(4),
      estimateHours: 6,
      spentHours: 0,
      tags: ['OP-TEE', '实验日志'],
      milestoneId: 'ms-experiment',
    }),
    task({
      id: 'task-snort-rule',
      title: 'Snort 规则调试',
      description: '编写并验证针对钓鱼链接和异常请求的 Snort 检测规则。',
      status: 'todo',
      priority: 'medium',
      module: 'practice',
      sourceLabel: '工具库',
      sourcePath: '/practice?tab=tools',
      assigneeId: 'member-wang',
      collaboratorIds: ['member-li'],
      startDate: addDays(1),
      dueDate: addDays(9),
      estimateHours: 5,
      spentHours: 0,
      tags: ['Snort', '检测规则'],
      milestoneId: 'ms-experiment',
    }),
    task({
      id: 'task-forum-team',
      title: '论坛组队需求更新',
      description: '更新团队缺口、分工、同步时间和本周交付要求。',
      status: 'todo',
      priority: 'low',
      module: 'forum',
      sourceLabel: '项目组队',
      sourcePath: '/forum?tab=team',
      assigneeId: 'member-zhao',
      collaboratorIds: ['member-chen'],
      startDate: addDays(0),
      dueDate: addDays(7),
      estimateHours: 2,
      spentHours: 0,
      tags: ['论坛', '组队'],
      milestoneId: 'ms-prototype',
    }),
    task({
      id: 'task-policy-checklist',
      title: '政策合规检查清单生成',
      description: '结合网络安全法、数据安全法和个人信息保护法整理答辩可用检查清单。',
      status: 'review',
      priority: 'medium',
      module: 'chat',
      sourceLabel: '政策解读',
      sourcePath: '/chat?tab=policy',
      assigneeId: 'member-liu',
      collaboratorIds: ['member-chen'],
      startDate: addDays(-1),
      dueDate: addDays(10),
      estimateHours: 3,
      spentHours: 2,
      tags: ['政策', '合规'],
      milestoneId: 'ms-submit',
    }),
  ];
}

function createActivities(tasks: TaskItem[]): TaskActivity[] {
  return tasks.slice(0, 7).map((task, index) => ({
    id: `activity-${task.id}`,
    taskId: task.id,
    type: task.status === 'done' ? 'completed' : 'created',
    actor: '系统',
    content: task.status === 'done' ? `完成任务：${task.title}` : `创建任务：${task.title}`,
    createdAt: new Date(Date.now() - index * 3600_000).toISOString(),
  }));
}

function deriveOrder(tasks: TaskItem[]): Record<TaskStatus, string[]> {
  return taskStatusOrder.reduce((acc, status) => {
    acc[status] = tasks.filter((taskItem) => taskItem.status === status).map((taskItem) => taskItem.id);
    return acc;
  }, {} as Record<TaskStatus, string[]>);
}

function attachMemberAssignments(teamMembers: TeamMember[], tasks: TaskItem[]): TeamMember[] {
  return teamMembers.map((member) => {
    const assigned = tasks.filter((item) => item.assigneeId === member.id && item.status !== 'done' && !item.archived);
    return {
      ...member,
      assignedTaskIds: assigned.map((item) => item.id),
      currentLoadHours: assigned.reduce((sum, item) => sum + item.estimateHours, 0),
    };
  });
}

export function createDefaultTaskWorkbench(): TaskWorkbench {
  const tasks = createDefaultTasks();
  const teamMembers = attachMemberAssignments(createDefaultTeamMembers(), tasks);
  const now = nowIso();

  return {
    id: 'tasks-workbench-demo',
    tasks,
    milestones: createDefaultMilestones(),
    teamMembers,
    activities: createActivities(tasks),
    filters: defaultFilters,
    currentMonth: monthIso(),
    boardColumnOrder: taskStatusOrder,
    taskOrderByStatus: deriveOrder(tasks),
    importedTaskIds: [],
    autosaveStatus: 'saved',
    savedAt: now,
    updatedAt: now,
  };
}
