Write-Host "SecureHub local development"
Write-Host ""
Write-Host "Frontend:"
Write-Host "  cd frontend"
Write-Host "  npm install"
Write-Host "  npm run dev"
Write-Host ""
Write-Host "Backend:"
Write-Host "  cd backend"
Write-Host "  uv sync"
Write-Host "  uv run uvicorn app.main:app --host 127.0.0.1 --port 8000 --reload"
Write-Host ""
Write-Host "Open:"
Write-Host "  Frontend: http://localhost:5173"
Write-Host "  Backend docs: http://127.0.0.1:8000/docs"
